version: '3'

services:
  postgresql:
    image: bitnami/postgresql
    container_name: rosa_blog_api
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=blog_db
    ports:
      - 5432:5432